# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bqFC_qWEmywfzqYpZ9c3kVFD10yp_eEw
"""

import csv
import json
import re
import urllib.request
import urllib.error
from datetime import datetime


def download_reviews():
    """
    Загрузка последних отзывов из Российского App Store
    по ID приложения.

    Пример:
        download_reviews(570060128)
    """

    app_id = input("Введите ID приложения App Store: ").strip()

    # Проверка ID
    if not re.fullmatch(r"\d+", app_id):
        print("Ошибка: ID приложения должен содержать только цифры.")
        return

    rss_url = (
        f"https://itunes.apple.com/ru/rss/customerreviews/"
        f"id={app_id}/sortBy=mostRecent/json"
    )

    print(f"ID приложения: {app_id}")
    print("Получение отзывов...")

    try:
        with urllib.request.urlopen(rss_url, timeout=30) as response:
            data = json.loads(response.read().decode("utf-8"))

    except urllib.error.HTTPError as e:
        print(f"Ошибка сервиса Apple: HTTP {e.code}")
        return

    except urllib.error.URLError as e:
        print(f"Ошибка подключения: {e.reason}")
        return

    except Exception as e:
        print(f"Неожиданная ошибка: {e}")
        return

    feed = data.get("feed")
    if not feed:
        print("Отзывы не найдены.")
        return

    entries = feed.get("entry", [])

    if len(entries) <= 1:
        print("Отзывы отсутствуют.")
        return

    # Первый элемент — информация о приложении
    entries = entries[1:]

    reviews = []
    russian_pattern = re.compile(r"[А-Яа-яЁё]")

    for item in entries:

        title = item.get("title", {}).get("label", "").strip()
        text = item.get("content", {}).get("label", "").strip()

        # Только русскоязычные отзывы
        if not russian_pattern.search(text):
            continue

        author = item.get("author", {}).get("name", {}).get("label", "").strip()
        rating = item.get("im:rating", {}).get("label", "")
        date = item.get("updated", {}).get("label", "")

        try:
            dt = datetime.strptime(date, "%Y-%m-%dT%H:%M:%S%z")
            date = dt.strftime("%Y-%m-%d %H:%M:%S")
        except:
            pass

        reviews.append([
            date,
            author,
            rating,
            text,
            title,
            "Россия"
        ])

        if len(reviews) % 10 == 0:
            print(f"Получено {len(reviews)} отзывов...")

    if not reviews:
        print("Русскоязычные отзывы не найдены.")
        return

    filename = f"reviews_{app_id}.csv"

    with open(filename, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f, delimiter=",")
        writer.writerow([
            "дата",
            "имя автора",
            "рейтинг",
            "текст отзыва",
            "заголовок",
            "страна"
        ])
        writer.writerows(reviews)

    print(f"\nГотово!")
    print(f"Сохранено отзывов: {len(reviews)}")
    print(f"Файл: {filename}")

download_reviews()